[ -f "$HOME/.config/xdg/env.zsh" ] && source "$HOME/.config/xdg/env.zsh"

# set ZSH directories
export ZDOTDIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh
export ZSH=$ZDOTDIR

# all of our .zsh files
typeset -U config_files
config_files=(${XDG_CONFIG_HOME:-$HOME/.config}/**/*.zsh)

# load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
do
  source $file
done

# if a secrets files exists load them
[[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/secrets ]] && source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/secrets
[[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/secrets.local ]] && source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/secrets.local

# initialize autocomplete here, otherwise functions won't be loaded
autoload -Uz compinit
compinit -d "${XDG_CONFIG_HOME:-$HOME/.config}"/zsh/zcompdump-"$ZSH_VERSION"

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}
do
  source $file
done

unset config_files
