#!/usr/bin/env zsh

if command -v vim >/dev/null 2>&1; then
  printf "\n\e[38;2;208;255;100m==>\e[0m \e[1;97mInstalling Vim plugins...\e[0m\n"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
