#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[aliases]
ll = ["log", "--template", "builtin_log_detailed"]
pull = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """
jj git fetch && jj rebase -d main@origin
"""
]

[git]
push-new-bookmarks = true

[signing]
behavior = "own"
backend = "gpg"
key = "87133702D8F60DD8"

[ui]
default-command = "log"
diff-formatter = ":git"
editor = "nvim"
pager = "delta"
paginate = "auto"
show-cryptographic-signatures = true

[user]
name = "Aaron Allen"
email = "hello@aaronmallen.me"
