#!/usr/bin/env sh

export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_CACHE_HOME="$HOME/Library/Caches"
export XDG_CONFIG_DIRS="${HOME}/Library/Preferences:/Library/Application Support:/Library/Preferences:${HOME}/.config"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_DIRS="/Library/Application Support:${HOME}/.local/share"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_RUNTIME_DIR="$HOME/Library/Application Support"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_VIDEOS_DIR="$HOME/Movies"
