#!/usr/bin/env zsh

if [ "$(uname -s)" = "Darwin" ]; then
  # Ask for the administrator password upfront
  sudo -v

  printf "\n\e[38;2;208;255;100m==>\e[0m \e[1;97mSetting macOS preferences...\e[0m\n"

  # Close any open System Preferences panes, to prevent them from overriding
  # settings we’re about to change
  osascript -e 'tell application "System Preferences" to quit'

  # =============================================================================
  # Appearance
  # =============================================================================

  # Enable dark mode
  osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'

  # =============================================================================
  # Finder Settings
  # =============================================================================

  # Ensure Finder always opens in List View
  defaults write com.apple.finder FXPreferredViewStyle -string Nlsv

  # Show hidden files in Finder
  defaults write com.apple.finder AppleShowAllFiles -bool true

  # =============================================================================
  # Dock Settings
  # =============================================================================

  # Set the icon size of Dock items
  defaults write com.apple.dock tilesize -int 26
  defaults write com.apple.dock magnification -bool true
  defaults write com.apple.dock largesize -int 128

  # Minimize windows into their application’s icon
  defaults write com.apple.dock minimize-to-application -bool true

  # Don't show recent applications in Dock
  defaults write com.apple.dock show-recents -bool false

  # Restart Finder and Dock for changes to take effect
  killall Finder
  killall Dock
fi
