#!/usr/bin/env sh

set -e

if ! command -v zsh >/dev/null 2>&1; then
  echo "==> Installing zsh"
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update && sudo apt-get install -y zsh
  elif command -v brew >/dev/null 2>&1; then
    brew install zsh
  elif command -v pacman >/dev/null 2>&1; then
    sudo pacman -S --noconfirm zsh
  else
    echo "Unable to install zsh. Please install it manually and try again."
    exit 1
  fi
fi

curl -fsSL https://raw.githubusercontent.com/aaronmallen/dotfiles/main/scripts/bootstrap | zsh
