name: Lint

permissions:
  contents: read
  pull-requests: write

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - name: Lint Editorconfig
        run: mise run lint:editorconfig
      - name: Lint Github Actions
        run: mise run lint:github-actions
      - name: Lint Markdown
        run: mise run lint:markdown
      - name: Lint TOML
        run: mise run lint:toml
      - name: Lint YAML
        run: mise run lint:yaml
